[workspace]
resolver = "2"
members = [
  "crates/store", "node", "test-programs/artifacts", "test-programs/cli", "test-programs/runner",]

exclude = [
"bitcoin-wasm",
   "lightning-wasm",
  "wallet",
]
